# SPDX-FileCopyrightText: 2025 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: CC0-1.0

[graph]
all-features = true

[advisories]
version = 2

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
  # TODO: add stuff here!
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.8
allow = [
  "MIT",
]
